secrets:
  CLICKHOUSE_PASSWORD: ""
  RABBITMQ_PASSWORD: ""
  RABBITMQ_ERLANG_COOKIE: ""

clickhouse:
  auth:
    existingSecret: credentials
    existingSecretKey: clickhouse-password

rabbitmq:
  auth:
    existingPasswordSecret: credentials
    existingErlangSecret: credentials

airflow:
  airflow:
    connections:
      - id: kubernetes_default
        type: kubernetes
        in_cluster: true
      - id: rabbitmq
        type: amqp
        host: ${RABBITMQ_SERVICE_HOST}
        port: 5672
        login: user
        password: ${RABBITMQ_PASSWORD}
    connectionsTemplates:
      RABBITMQ_PASSWORD:
        kind: secret
        name: credentials
        key: rabbitmq-password
    extraPipPackages:
      - "airflow-provider-rabbitmq"
      - "requests"
  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/karatach1998/HousePriceEstimator.git"
      branch: master
      revision: "HEAD"
      repoSubPath: "airflow"
      syncWait: 60