secrets:
  clickhousePassword: ""
  rabbitmqPassword: ""
  rabbitmqErlangCookie: ""

clickhouse:
  auth:
    existingSecret: credentials
    existingSecretKey: clickhouse-password
  shards: 1
  replicaCount: 1

rabbitmq:
  auth:
    existingPasswordSecret: credentials
    existingErlangSecret: credentials

redis:
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence, AOF persistence already enabled.
    save ""

airflow:
  airflow:
    connections:
      - id: kubernetes_default
        type: kubernetes
        in_cluster: true
      - id: rabbitmq_default
        type: amqp
        host: housepriceestimator-rabbitmq.default.svc.cluster.local
        port: 5672
        login: user
        password: ${RABBITMQ_PASSWORD}
      - id: clickhouse_default
        type: clickhouse
        host: housepriceestimator-clickhouse-shard0-0.housepriceestimator-clickhouse-headless.default.svc.cluster.local
        login: default
        password: ${CLICKHOUSE_PASSWORD}
      - id: http_flower
        type: http
        host: scrapper-flower.scrapper.svc.cluster.local
        port: 5555
        schema: http
    connectionsTemplates:
      RABBITMQ_PASSWORD:
        kind: secret
        name: credentials
        key: rabbitmq-password
      CLICKHOUSE_PASSWORD:
        kind: secret
        name: credentials
        key: clickhouse-password
    extraPipPackages:
      - "apache-airflow-providers-cncf-kubernetes"
      - "apache-airflow-providers-http"
      - "kubernetes"
      - "requests"
  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/karatach1998/HousePriceEstimator.git"
      branch: master
      revision: "HEAD"
      repoSubPath: "airflow"
      syncWait: 60
  redis:
    enabled: false
  externalRedis:
    host: housepriceestimator-redis-master
    databaseNumber: 2