secrets:
  CLICKHOUSE_PASSWORD: ""
  RABBITMQ_PASSWORD: ""

clickhouse:
  auth:
    existingSecret: credentials
    existingSecretKey: clickhouse-password

rabbitmq:
  auth:
    existingPasswordSecret: credentials