apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  clickhouse-password: {{ required "ClickHouse password must be provided" .Values.secrets.clickhousePassword | b64enc | quote }}
  rabbitmq-password: {{ required "RabbitMQ password must be provided" .Values.secrets.rabbitmqPassword | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ required "RabbitMQ Erlang Cookie must be provided" .Values.secrets.rabbitmqErlangCookie | b64enc | quote }}