apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  clickhouse-password: {{ required "ClickHouse password must be provided" .Values.secrets.clickhousePassword | b64enc | quote }}
  rabbitmq-password: {{ required "RabbitMQ password must be provided" .Values.secrets.rabbitmqPassword | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ required "RabbitMQ Erlang Cookie must be provided" .Values.secrets.rabbitmqErlangCookie | b64enc | quote }}
  aws-access-key-id: {{ required "Access key ID for your S3 must be provided" .Values.secrets.awsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ required "Secret access key for your S3 must be provided" .Values.secrets.awsSecretAccessKey | b64enc | quote }}