apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoinfo
  template:
    metadata:
      labels:
        app: geoinfo
    spec:
      containers:
        - name: geoinfo
          image: ghcr.io/karatach1998/geoinfo:latest
          imagePullPolicy: Always
          command: ["poetry", "run", "gunicorn", "geo_info.main:app", "--workers=8", "--worker-class=uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8060"]
          ports:
            - containerPort: 8060
              protocol: TCP