apiVersion: v1
kind: Service
metadata:
  name: model-server
spec:
  type: ClusterIP
  selector:
    app: model-server
  ports:
    - port: 16080
      targetPort: http
      protocol: TCP
      name: http