apiVersion: v1
kind: Service
metadata:
  name: model_server
spec:
  type: ClusterIP
  selector:
    app: model_server
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http