apiVersion: v1
kind: Service
metadata:
  name: model-server
spec:
  type: ClusterIP
  selector:
    app: model-server
  ports:
    - port: 8080
      targetPort: 8100
      protocol: TCP
      name: http