name: build-and-deploy
on: [push]
jobs:
  build-model-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./model_server
          push: true
          tags: karatach1998/model-server:latest
  
  # deploy-to-k8s:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Helm Deploy
  #       uses: vimeda/helm@v1.6.8
  #       with:
  #         release: ''
  #         namespace: 'default'
  #         chart: 'charts/housepriceestimator'
  #         token: '${{ github.token }}'
  #         values: {}
  #       env:
  #         KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'